/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-10-05 16:33:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class apply_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

 String role = (String) session.getAttribute("role");
 if (role == null || !"student".equals(role)) { 
    response.sendRedirect("login.jsp"); 
    return; 
 }
 String jobId = request.getParameter("jobId");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Apply for Job</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: \"Segoe UI\", Arial, sans-serif;\r\n");
      out.write("            background: #f5f7fa;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header {\r\n");
      out.write("            background: #2563eb;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 15px 40px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            box-shadow: 0 3px 10px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header h2 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logout-btn {\r\n");
      out.write("            background: #f43f5e;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 8px 16px;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logout-btn:hover {\r\n");
      out.write("            background: #dc2626;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            margin: 60px auto;\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 30px 40px;\r\n");
      out.write("            box-shadow: 0 2px 15px rgba(0,0,0,0.08);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #000000;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        form {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        form input[type=\"text\"],\r\n");
      out.write("        form input[type=\"number\"],\r\n");
      out.write("        form input[type=\"file\"],\r\n");
      out.write("        form input[type=\"hidden\"],\r\n");
      out.write("        form input[name],\r\n");
      out.write("        form textarea {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px 12px;\r\n");
      out.write("            border: 1px solid #d1d5db;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        form label {\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            color: #1e3a8a;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        form button {\r\n");
      out.write("            background: #2563eb;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 10px 18px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background 0.3s;\r\n");
      out.write("            align-self: flex-end;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        form button:hover {\r\n");
      out.write("            background: #1d4ed8;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: green;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-link {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-link a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-link a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #6b7280;\r\n");
      out.write("            padding: 15px 0;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .form-container {\r\n");
      out.write("                margin: 30px 15px;\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <h2>Apply for Job</h2>\r\n");
      out.write("        <div>\r\n");
      out.write("            <span>Welcome, Student</span>\r\n");
      out.write("            <form action=\"login.jsp\" method=\"post\" style=\"display:inline;\">\r\n");
      out.write("                <button class=\"logout-btn\">Logout</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"form-container\">\r\n");
      out.write("        <c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            <p class=\"message\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("        </c:if>\r\n");
      out.write("\r\n");
      out.write("        <form method=\"post\" action=\"apply\" enctype=\"multipart/form-data\">\r\n");
      out.write("            <input type=\"hidden\" name=\"jobId\" value=\"");
      out.print(jobId);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("            <input name=\"name\" placeholder=\"Full Name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.fullname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("            <input name=\"degree\" placeholder=\"Degree\" required>\r\n");
      out.write("            <input name=\"cgpa\" placeholder=\"CGPA\" required>\r\n");
      out.write("            <input name=\"backlogs\" placeholder=\"Backlogs (if any)\">\r\n");
      out.write("            \r\n");
      out.write("            <label>Upload Resume (PDF/DOC):</label>\r\n");
      out.write("            <input type=\"file\" name=\"resume\" accept=\".pdf,.doc,.docx\" required>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\">Submit Application</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"back-link\">\r\n");
      out.write("            <a href=\"student.jsp\">â Back to Dashboard</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        Â© 2025 Campus Recruitment Portal â Application Page\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
