/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-10-05 16:32:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.example.portal.DBUtil;

public final class recruiter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.example.portal.DBUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

  String role = (String) session.getAttribute("role");
  if (role == null || !"recruiter".equals(role)) {
    response.sendRedirect("login.jsp");
    return;
  }

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Recruiter Dashboard</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: \"Segoe UI\", Arial, sans-serif;\r\n");
      out.write("            background: #f4f7fb;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header {\r\n");
      out.write("            background: #1e3a8a;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 15px 40px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            box-shadow: 0 3px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header h2 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1000px;\r\n");
      out.write("            margin: 40px auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h3 {\r\n");
      out.write("            color: #1e3a8a;\r\n");
      out.write("            border-left: 4px solid #1e3a8a;\r\n");
      out.write("            padding-left: 10px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        form {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            padding: 25px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.08);\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        form input, form textarea {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border: 1px solid #d1d5db;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        form textarea {\r\n");
      out.write("            resize: vertical;\r\n");
      out.write("            height: 80px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        form button {\r\n");
      out.write("            background: #2563eb;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        form button:hover {\r\n");
      out.write("            background: #1d4ed8;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logout-btn {\r\n");
      out.write("            background: #f43f5e;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 8px 16px;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logout-btn:hover {\r\n");
      out.write("            background: #dc2626;\r\n");
      out.write("Â Â Â Â Â Â Â Â }\r\n");
      out.write("\r\n");
      out.write("        .job {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 1px 8px rgba(0, 0, 0, 0.06);\r\n");
      out.write("            transition: transform 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .job:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .job strong {\r\n");
      out.write("            color: #111827;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .job p {\r\n");
      out.write("            margin: 6px 0;\r\n");
      out.write("            line-height: 1.4;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .job a {\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .job a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #6b7280;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            padding: 15px 0;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <h2>Recruiter Dashboard</h2>\r\n");
      out.write("        <div>\r\n");
      out.write("            <span>Welcome, Recruiter</span>\r\n");
      out.write("            <form action=\"login.jsp\" method=\"post\" style=\"display:inline;\">\r\n");
      out.write("                <button class=\"logout-btn\">Logout</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h3>Post a Job</h3>\r\n");
      out.write("        <form method=\"post\" action=\"postJob\">\r\n");
      out.write("            <input name=\"companyName\" placeholder=\"Company Name\" required>\r\n");
      out.write("            <input name=\"title\" placeholder=\"Job Title\" required>\r\n");
      out.write("            <textarea name=\"description\" placeholder=\"Job Description\"></textarea>\r\n");
      out.write("            <input name=\"eligibility\" placeholder=\"Eligibility\">\r\n");
      out.write("            <input name=\"ctc\" placeholder=\"CTC\">\r\n");
      out.write("            <button type=\"submit\">Submit</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <h3>Your Posted Jobs</h3>\r\n");
      out.write("        ");

            java.sql.Connection conn = null;
            java.sql.PreparedStatement ps = null;
            java.sql.ResultSet rs = null;
            try {
                conn = DBUtil.getConnection();
                ps = conn.prepareStatement("SELECT * FROM jobs WHERE posted_by = ? ORDER BY posted_at DESC");
                ps.setInt(1, (Integer) session.getAttribute("userId"));
                rs = ps.executeQuery();
                boolean hasJobs = false;
                while (rs.next()) {
                    hasJobs = true;
        
      out.write("\r\n");
      out.write("        <div class=\"job\">\r\n");
      out.write("            <strong>");
      out.print( rs.getString("title") );
      out.write("</strong> - ");
      out.print( rs.getString("company_name") );
      out.write("\r\n");
      out.write("            <p>");
      out.print( rs.getString("description") );
      out.write("</p>\r\n");
      out.write("            <p><strong>Eligibility:</strong> ");
      out.print( rs.getString("eligibility") );
      out.write(" | <strong>CTC:</strong> ");
      out.print( rs.getString("ctc") );
      out.write("</p>\r\n");
      out.write("            <a href=\"viewApplications?jobId=");
      out.print( rs.getInt("id") );
      out.write("\">View Applications</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

                }
                if (!hasJobs) {
        
      out.write("\r\n");
      out.write("        <p style=\"color: #6b7280;\">No jobs posted yet.</p>\r\n");
      out.write("        ");

                }
            } catch (Exception e) {
                out.println("<p style='color:red;'>Error: " + e.getMessage() + "</p>");
            } finally {
                DBUtil.close(rs, ps, conn);
            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        Â© 2025 Campus Recruitment Portal â Recruiter Panel\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
